version: '2'
services:
  poker_project:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - poker_project-db
    environment:
      - PASSENGER_APP_ENV=development
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=poker_project.dev.com
      - RAILS_LOG_TO_STDOUT=true
    ports:
      - "80"
    volumes:
      - .:/home/app/webapp
  poker_project-db:
    image: postgres:9.5.2
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=poker
      - POSTGRES_DB=poker_development
    volumes_from:
      - poker_project-db-data
    ports:
      - "5432"
  poker_project-db-data:
    image: postgres:9.5.2
    volumes:
      - /var/lib/postgresql/data
    command: /bin/true

    networks:
      - default
      - poker

networks:
  poker:
    driver: bridge
